name: OnTrack Task Validator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Test with Maven
      run: mvn test
      
    - name: Create build status comment
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const buildStatus = "${{ job.status }}".toLowerCase() === "success" ? "✅ Build succeeded" : "❌ Build failed";
          
          // For pull requests
          if (context.payload.pull_request) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: buildStatus
            });
          }
          
          // For commits to main, create a issue with status
          if (context.payload.ref === 'refs/heads/main' && "${{ job.status }}".toLowerCase() === "failure") {
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Build Failure on Commit ${context.sha.substring(0, 7)}`,
              body: `The build failed on commit [${context.sha.substring(0, 7)}](https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}).`
            });
          }
